/**
 * This file implements a catch-all route that renders the user-facing pages
 * generated by CredBuild. For any route visited (with exception of other hardcoded
 * pages in /app), it will check your database (via `getPage`) for a CredBuild page
 * and render it using <Render>.
 *
 * All routes produced by this page are statically rendered using incremental
 * static site generation. After the first visit, the page will be cached as
 * a static file. Subsequent visits will receive the cache. Publishing a page
 * will invalidate the cache as the page is written in /api/credbuild/route.ts
 */

import { Client } from "./client";
import { notFound } from "next/navigation";
import { Metadata } from "next";
import { getPage } from "../../../lib/get-page";
import TiptapRenderer from "@/components/TiptapRenderer";
import { hooks } from "../../../lib/hooks";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ credbuildPath: string[] }>;
}): Promise<Metadata> {
  const { credbuildPath = [] } = await params;
  const path = `/${credbuildPath.join("/")}`;
  const pageData = await getPage(path);

  const ogTitle = pageData?.title || pageData?.data?.root?.props?.title;
  const ogDescription = pageData?.description;

  return {
    title: ogTitle,
    description: ogDescription,
    openGraph: {
      ...(ogTitle && { title: ogTitle }),
      ...(ogDescription && { description: ogDescription }),
      images: pageData?.imageUrl ? [{ url: pageData.imageUrl }] : undefined,
    },
  };
}

export default async function Page({
  params,
}: {
  params: Promise<{ credbuildPath: string[] }>;
}) {
  const { credbuildPath = [] } = await params;
  const path = `/${credbuildPath.join("/")}`;
  let data = await getPage(path);

  // Apply filters to page data
  data = hooks.applyFilters("page_data", data, { path });

  if (!data) {
    return notFound();
  }

  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "WebPage",
    "headline": data.title || "Page",
    "description": data.description,
    "url": `${baseUrl}${path}`,
    "image": data.imageUrl ? [data.imageUrl] : undefined,
    "datePublished": data.createdAt,
    "dateModified": data.updatedAt,
  };

  // Render Visual Builder content if it exists and useBuilder is true
  if (data.useBuilder) {
    return (
      <>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <Client data={data.data} />
      </>
    );
  }

  // If we have a standard body (Not using CredBuild), render it directly
  if (data.body && data.body !== "" && data.body !== "{}" && data.body !== '{"type":"doc","content":[]}') {
    return (
      <div className="min-h-screen bg-white">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <div className="max-w-4xl mx-auto px-6 py-12 lg:px-8">
          <header className="mb-10 text-center">
            {data.title && <h1 className="text-4xl font-extrabold text-gray-900 sm:text-5xl">{data.title}</h1>}
          </header>
          <TiptapRenderer content={data.body} />
        </div>
      </div>
    );
  }

  // Default fallback (empty builder canvas or not found)
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <Client data={data.data} />
    </>
  );
}

// Force Next.js to produce static pages: https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#dynamic
// Delete this if you need dynamic rendering, such as access to headers or cookies
export const dynamic = "force-static";
