/**
 * This file implements a catch-all route that renders the user-facing pages
 * generated by Puck. For any route visited (with exception of other hardcoded
 * pages in /app), it will check your database (via `getPage`) for a Puck page
 * and render it using <Render>.
 *
 * All routes produced by this page are statically rendered using incremental
 * static site generation. After the first visit, the page will be cached as
 * a static file. Subsequent visits will receive the cache. Publishing a page
 * will invalidate the cache as the page is written in /api/puck/route.ts
 */

import { Client } from "./client";
import { notFound } from "next/navigation";
import { Metadata } from "next";
import { getPage } from "../../../lib/get-page";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ puckPath: string[] }>;
}): Promise<Metadata> {
  const { puckPath = [] } = await params;
  const path = `/${puckPath.join("/")}`;
  const pageData = await getPage(path);

  return {
    title: pageData?.title || pageData?.data?.root?.props?.title,
    description: pageData?.description,
    openGraph: {
      title: pageData?.title || pageData?.data?.root?.props?.title,
      description: pageData?.description,
      images: pageData?.imageUrl ? [{ url: pageData.imageUrl }] : undefined,
    },
  };
}

export default async function Page({
  params,
}: {
  params: Promise<{ puckPath: string[] }>;
}) {
  const { puckPath = [] } = await params;
  const path = `/${puckPath.join("/")}`;
  const data = await getPage(path);

  if (!data) {
    return notFound();
  }

  // If we have a standard body (Not using Puck), render it directly
  if (data.body) {
    return (
      <div className="min-h-screen bg-white">
        <div className="max-w-4xl mx-auto px-6 py-12 lg:px-8">
          <header className="mb-10 text-center">
            {data.title && <h1 className="text-4xl font-extrabold text-gray-900 sm:text-5xl">{data.title}</h1>}
          </header>
          <div className="prose prose-lg mx-auto text-gray-600" dangerouslySetInnerHTML={{ __html: data.body }} />
        </div>
      </div>
    );
  }

  return <Client data={data.data} />;
}

// Force Next.js to produce static pages: https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#dynamic
// Delete this if you need dynamic rendering, such as access to headers or cookies
export const dynamic = "force-static";
